theme: jekyll-theme-minimal
title: Freeform Universal Consensually Kinky (FUCK) RPG
logo: /img/favicon.ico
description: Freeform Universal Consensually Kinky (FUCK) RPG system. A 18+, for adults only, table top RPG style system based on sex and kinks. Meant to make adventuring with leather, whips and chains; safe, sane and consensual.
